/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package waterbottle;

import org.junit.Test;
import static org.junit.Assert.*;

import org.junit.After;
import org.junit.Before;

public class WaterBottleTest {
	
	private Laboratory lab;
	
	private Bottle bottle5l;
	private Bottle bottle3l;
	
	@Before
	public void setUp() throws Exception {
		bottle5l = new Bottle(5);
		bottle3l = new Bottle(3);
		lab = new Laboratory(bottle3l, bottle5l, 1);
	}

	@After
	public void tearDown() throws Exception {
		bottle5l = null;
		bottle3l = null;
	}
	
    @Test
    public void testCreateBottles() {
    	assertEquals("Bottle size should be 5", 5, bottle5l.getSize());
    	assertEquals("Bottle size should be 3", 3, bottle3l.getSize());
    }
	
    @Test
    public void testFillBottle() {
    	bottle3l.fill();
    	bottle5l.fill();
    	assertEquals("Bottle water volume should be 5", 5, bottle5l.getVolume());
    	assertEquals("Bottle water volume should be 3", 3, bottle3l.getVolume());
    }
    
    @Test
    public void testFill3LFrom5L() {
    	bottle5l.fill();
    	lab.transfer(bottle5l, bottle3l);
    	assertEquals("3L bottle should be full", 3, bottle3l.getVolume());
    	assertEquals("5l bottle should have 2l left", 2, bottle5l.getVolume());
    }
    
    @Test
    public void testFill5LFrom3L() {
    	bottle3l.fill();
    	lab.transfer(bottle3l, bottle5l);
    	assertEquals("3L bottle should be empty", 0, bottle3l.getVolume());
    	assertEquals("5l bottle should have 3l", 3, bottle5l.getVolume());
    }
    
    @Test
    public void testFill5LWithWaterfrom3L() {
    	bottle5l.setVolume(3);
    	bottle3l.fill();
    	lab.transfer(bottle3l, bottle5l);
    	assertEquals("5L bottle should be full", 5, bottle5l.getVolume());
    	assertEquals("3l bottle should have 2l left", 1, bottle3l.getVolume());
    }
}
